// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240629062533_AddAmenityTableToDb")]
    partial class AddAmenityTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A small private heated pool",
                            Name = "Private pool",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A small private cold water pool",
                            Name = "Private pool",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A small private heated pool and a small private cold water pool",
                            Name = "Private pool",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "A parking space for the car",
                            Name = "Parking",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "free parking",
                            Name = "Parking",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Unlimited free WIFI",
                            Name = "Free WIFI",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Unlimited free WIFI",
                            Name = "Free WIFI",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Unlimited free WIFI",
                            Name = "Free WIFI",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hotel Royal is a hotel located in many cities around the world. It is a hotel brand that operates multiple properties in different locations.",
                            ImageUrl = "~/Images/royal.jpg",
                            Name = "Royal",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 250
                        },
                        new
                        {
                            Id = 2,
                            Description = "The term \"poor hotel\" doesn't have a widely recognized or standard definition. It's a somewhat subjective and vague term that could mean different things to different people. ",
                            ImageUrl = "~/Images/poor.jpg",
                            Name = "Poor",
                            Occupancy = 1,
                            Price = 50.0,
                            Sqft = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "A KingsHotel typically refers to a hotel that has the word Kings in its name, implying it is a hotel that aims to provide an upscale, high-end, or luxurious experience for its guests.",
                            ImageUrl = "~/Images/kings.jpg",
                            Name = "Kings",
                            Occupancy = 6,
                            Price = 400.0,
                            Sqft = 500
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.Property<int>("Villa_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Villa_Number");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            Villa_Number = 101,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 102,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 103,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 104,
                            VillaId = 1
                        },
                        new
                        {
                            Villa_Number = 201,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 202,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 203,
                            VillaId = 2
                        },
                        new
                        {
                            Villa_Number = 301,
                            VillaId = 3
                        },
                        new
                        {
                            Villa_Number = 302,
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.VillaNumber", b =>
                {
                    b.HasOne("WhiteLagoon.Domain.Entities.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
