// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240602104728_SeedDataInVillasTable")]
    partial class SeedDataInVillasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hotel Royal is a hotel located in many cities around the world. It is a hotel brand that operates multiple properties in different locations.",
                            ImageUrl = "~/Images/royal.jpg",
                            Name = "Royal",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 250
                        },
                        new
                        {
                            Id = 2,
                            Description = "The term \"poor hotel\" doesn't have a widely recognized or standard definition. It's a somewhat subjective and vague term that could mean different things to different people. ",
                            ImageUrl = "~/Images/poor.jpg",
                            Name = "Poor",
                            Occupancy = 1,
                            Price = 50.0,
                            Sqft = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "A KingsHotel typically refers to a hotel that has the word Kings in its name, implying it is a hotel that aims to provide an upscale, high-end, or luxurious experience for its guests.",
                            ImageUrl = "~/Images/kings.jpg",
                            Name = "Kings",
                            Occupancy = 6,
                            Price = 400.0,
                            Sqft = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
